add_test( [==[float methods validate against std::sqrt]==] /home/blaze/Blaze/Projects/sqrt_bench/build_full/sqrt_bench_tests [==[float methods validate against std::sqrt]==]  )
set_tests_properties( [==[float methods validate against std::sqrt]==] PROPERTIES WORKING_DIRECTORY /home/blaze/Blaze/Projects/sqrt_bench/build_full)
add_test( [==[double methods validate against std::sqrt]==] /home/blaze/Blaze/Projects/sqrt_bench/build_full/sqrt_bench_tests [==[double methods validate against std::sqrt]==]  )
set_tests_properties( [==[double methods validate against std::sqrt]==] PROPERTIES WORKING_DIRECTORY /home/blaze/Blaze/Projects/sqrt_bench/build_full)
add_test( [==[float methods reject non-positive and non-finite inputs]==] /home/blaze/Blaze/Projects/sqrt_bench/build_full/sqrt_bench_tests [==[float methods reject non-positive and non-finite inputs]==]  )
set_tests_properties( [==[float methods reject non-positive and non-finite inputs]==] PROPERTIES WORKING_DIRECTORY /home/blaze/Blaze/Projects/sqrt_bench/build_full)
add_test( [==[double methods reject non-positive and non-finite inputs]==] /home/blaze/Blaze/Projects/sqrt_bench/build_full/sqrt_bench_tests [==[double methods reject non-positive and non-finite inputs]==]  )
set_tests_properties( [==[double methods reject non-positive and non-finite inputs]==] PROPERTIES WORKING_DIRECTORY /home/blaze/Blaze/Projects/sqrt_bench/build_full)
set( sqrt_bench_tests_TESTS [==[float methods validate against std::sqrt]==] [==[double methods validate against std::sqrt]==] [==[float methods reject non-positive and non-finite inputs]==] [==[double methods reject non-positive and non-finite inputs]==])
