if(EXISTS "/home/blaze/Blaze/Projects/sqrt_bench/build_full/sqrt_bench_tests-b12d07c_tests.cmake")
  include("/home/blaze/Blaze/Projects/sqrt_bench/build_full/sqrt_bench_tests-b12d07c_tests.cmake")
else()
  add_test(sqrt_bench_tests_NOT_BUILT-b12d07c sqrt_bench_tests_NOT_BUILT-b12d07c)
endif()
